#!/tmp/mnt/usbstick/entware/bin/bash
#Requires bash and xmlstarlet

if [[ $# -ne 1 ]] ; then
        echo './dns.sh NEW-IP'
        exit 0
fi

# Update the following variables:
USERNAME=xxxxx
PASSWORD=xxxxx
TLD=eu
SLD=vault13


# Change nothing below this point
DOMAIN=$SLD.$TLD
NEWIP=$1
echo "<x:Envelope xmlns:x=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:urn=\"urn:syncer\">
    <x:Header/>
    <x:Body>
        <urn:ListDnsRecords>
            <urn:sld>$SLD</urn:sld>
            <urn:tld>$TLD</urn:tld>
            <urn:login_handle>$USERNAME</urn:login_handle>
            <urn:login_password>$PASSWORD</urn:login_password>
        </urn:ListDnsRecords>
    </x:Body>
</x:Envelope>" > list.xml

soapresponse=$(curl --silent --header "Content-Type: text/xml;charset=UTF-8" --header "SOAPAction:urn:syncer#ListDnsRecords" --data @list.xml http://api.syncer.com/index.php)
SUBDOMAINS=$(printf '%s\n' "$soapresponse" | xml sel -t -m "//item[type='A']" -v "name" -o " ")
array=( $SUBDOMAINS )
OLDIP=$(printf '%s\n' "$soapresponse" | xml sel -t -m "//item[1][type='A']" -v "data")

if [ "$OLDIP" == "$NEWIP" ] ; then
    echo 'IP Address not changed, aborting!'
    exit 0
fi

# update every subdomain (A-Record)
for i in "${array[@]}"
do

#echo Calling: xml sel -t -m "//item[name='$i']" -v "data"
IP=$(printf '%s\n' "$soapresponse" | xml sel -t -m "//item[name='$i']" -v "data")
echo Replacing $OLDIP with $NEWIP for $i, which currently has IP $IP

if ! [ "$OLDIP" == "$IP" ] ; then
    echo 'Custom IP Address $IP, aborting!'
    continue
fi


echo deleting $i
echo "<x:Envelope xmlns:x=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:urn=\"urn:syncer\">
    <x:Header/>
    <x:Body>
        <urn:DeleteDnsRecord>
            <urn:domain>$DOMAIN</urn:domain>
            <urn:name>$i</urn:name>
            <urn:type>A</urn:type>
            <urn:data>$OLDIP</urn:data>
            <urn:login_handle>$USERNAME</urn:login_handle>
            <urn:login_password>$PASSWORD</urn:login_password>
        </urn:DeleteDnsRecord>
    </x:Body>
</x:Envelope>" > delete.xml

#echo Press any key to continue && read -n 1 -s
curl --silent --header "Content-Type: text/xml;charset=UTF-8" --header "SOAPAction:urn:syncer#DeleteDnsRecord" --data @delete.xml http://api.syncer.com/index.php >/dev/null 2>&1
rm delete.xml

echo creating $i
echo "<x:Envelope xmlns:x=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:urn=\"urn:syncer\">
    <x:Header/>
    <x:Body>
        <urn:AddDnsRecord>
            <urn:domain>$DOMAIN</urn:domain>
            <urn:name>$i</urn:name>
            <urn:dnstype>A</urn:dnstype>
            <urn:data>$NEWIP</urn:data>
            <urn:options>array(\"overwrite:yes\");</urn:options>
            <urn:login_handle>$USERNAME</urn:login_handle>
            <urn:login_password>$PASSWORD</urn:login_password>
        </urn:AddDnsRecord>
    </x:Body>
</x:Envelope>" > request.xml

#echo Press any key to continue && read -n 1 -s
curl --silent --header "Content-Type: text/xml;charset=UTF-8" --header "SOAPAction:urn:syncer#AddDnsRecord" --data @request.xml http://api.syncer.com/index.php >/dev/null 2>&1
rm request.xml
done
rm list.xml

if [ $? -eq 0 ];
then
    /sbin/ddns_custom_updated 1
else
    /sbin/ddns_custom_updated 0
fi
